### PR TITLE
[Feature Request] Add Read Marker Status column to manga page

### PR DESCRIPTION
**Pull request by JSaurusRex**
This adds the mangadex read marker to the chapter list
image
_ meaning not read
R meaning have read

### CODE REVIEW

**Review by darylhjd — COMMENTED** [review]
Thanks for the contribution!

A few comments for discussion:
- Getting read markers should not be a returning error as it is not vital information.
    - If the API fails, we should just leave the field blank or perhaps use "?" (I am in favour of "?")
- If the chapter has not been read, we can just leave a blank string instead of "_".

Let me know what you think.

**Comment by darylhjd** [comment]
Also, there might need to have a check as to whether the client is logged in or not.

**Comment by scott-tancock** [comment]
This should fix #16.

For the read markers, might I suggest ✓ and ✗?  These symbols should be pretty unambiguous.  I've checked they work correctly.

**Comment by darylhjd** [comment]
emojis come out weird for different os and the colouring might be off. on linux the tick is black which is unreadable.

i prefer blank entries for non-read to reduce text render.

**Comment by darylhjd** [comment]
will only approve this after #14 is closed.

**Pull request merged**
