### PR TITLE
Add Zip and Cbz File Downloads

### PR DESCRIPTION
**Pull request by henry726**
Adds a new setting in the config file called "exportType". 0 is for a basic folder download (default), 1 is for zip file, and 2 is for cbz file.

### CODE REVIEW

**Comment by darylhjd** [comment]
is there a convincing use case for zip file downloads?

**Comment by henry726** [comment]
Not really, I just added it cause the self-hosted manga server I use supports zip files as a file format, along with cbz. If I'm not mistaken, cbz files are basically just renamed zip files, so I aggree it might be redundant to support them both. I can remove it if needed.

**Comment by darylhjd** [comment]
ok im thinking about cleaning up the codebase a little before i consider this

**Comment by darylhjd** [comment]
honestly i would be more open to a PDF download rather than a zip.

**Comment by darylhjd** [comment]
pull request can no longer be merged without conflict, as such I will be closing it. 

for future pull requests, try to open an issue first so we can perhaps discuss the addition of the feature before you commit to writing code. this will save you time.

sorry!

**Pull request closed without merging**
